// import img from '../assets/images/avatar1.jpg'

const obj = [
    {
        id:1,
        image:"image1.jpg",
        size:''
        
    },
    {
        id:2,
        image:"image2.jpg",
        size:'tall'
    },
    {
        id:3,
        image:"image3.jpg",
        size:'tall'
    },
    {
        id:4,
        image:"image4.jpg",
        size:''
    },
    {
        id:5,
        image:"image5.jpg",
        size:'tall'
    },
    {
        id:6,
        image:"image6.jpg",
        size:''
    },
    {
        id:7,
        image:"image7.jpg",
        size:''
    },
    {
        id:8,
        image:"image8.jpg",
        size:'tall'
    },
    {
        id:9,
        image:"image9.jpg",
        size:''
    },
    {
        id:10,
        image:"image10.jpg",
        size:''
    },
    {
        id:11,
        image:"image11.jpg",
        size:'tall'
    },
    {
        id:12,
        image:"image12.jpg",
        size:''
    },
    {
        id:13,
        image:"image13.jpg",
        size:'wide'
    },
    {
        id:14,
        image:"image14.jpg",
        size:'tall'
    },
    {
        id:15,
        image:"image15.jpg",
        size:'wide'
    },
    
]

export default obj;